stages:          # List of stages for jobs, and their order of execution
  - build
  - run

build:       # This job runs in the build stage, which runs first.
  stage: build
  artifacts:
    untracked: true
  script:
    - git submodule update --init --recursive
    - echo "Updating dependencies"
    - bash
    - source ~/.bashrc
    - conda activate dumpoci
    - pip install -e .
    - unzip -o dumpotest/third_party/AmbiqSuite-4.zip -d dumpotest/third_party/
    - rm -f dumpotest/out.txt

run:   # This job runs in the test stage.
  stage: run    # It only starts when the job in the build stage completes successfully.
  dependencies: 
    - build
  script:
    - git submodule update --init --recursive
    - bash
    - source ~/.bashrc
    - export PATH="~scheremo/gcc-arm/bin:$PATH"
    - export LD_LIBRARY_PATH="~scheremo/.local/JLink_Linux_V770c_x86_64/:$LD_LIBRARY_PATH"
    - conda activate dumpoci
    - cd dumpotest
    - python testRunner.py --device=/dev/ttyACM1 -t ./Tests/simpleRegression
    
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./dumpotest/out.txt
