variables:
  GIT_SUBMODULE_STRATEGY: recursive
  FF_USE_FASTZIP: "true"
  # These can be specified per job or per pipeline
  ARTIFACT_COMPRESSION_LEVEL: "fastest"
  CACHE_COMPRESSION_LEVEL: "fastest"
  TOOLCHAIN: "LLVM"
  CMAKE_GENERATOR: "Ninja"

stages: # List of stages for jobs, and their order of execution
  - build
  - lint
  - test

build_deeploy: # This job runs in the build stage, which runs first.
  stage: build
  artifacts:
    untracked: true
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - pip install --ignore-install -e .
    - rm -f deeploytest/out.txt
    - rm -f deeploytest/TEST_*

run_cmsis_test_models: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  tags:
    - qemu-arm
  needs:
    - job: build_deeploy
      artifacts: false
  parallel:
    matrix:
    - TEST: [simpleRegression, WaveFormer]
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testRunner_qemu.py -t ./Tests/$TEST --toolchain=$TOOLCHAIN --toolchain_install_dir=$LLVM_INSTALL_DIR
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./deeploytest/out.txt
      - ./deeploytest/TEST_QEMU/Tests/$TEST/*.c
      - ./deeploytest/TEST_QEMU/Tests/$TEST/*.h
  cache:
    key: $CI_RUNNER_ID-$CI_CONCURRENT_ID-$CI_COMMIT_REF_SLUG
    paths:
      - ./deeploytest/TEST_*/build

run_cmsis_test_kernels: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  tags:
    - qemu-arm
  needs:
    - job: build_deeploy
      artifacts: false
  parallel:
    matrix:
    - TEST: [Adder, MultIO, test1DPad, test2DPad, testMatMul, testMatMulAdd, testMaxPool, testRQConv, testReduceSum, testReduceMean, testSlice]
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testRunner_qemu.py -t ./Tests/$TEST --toolchain=$TOOLCHAIN --toolchain_install_dir=$LLVM_INSTALL_DIR
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./deeploytest/out.txt
      - ./deeploytest/TEST_QEMU/Tests/$TEST/*.c
      - ./deeploytest/TEST_QEMU/Tests/$TEST/*.h
  cache:
    key: $CI_RUNNER_ID-$CI_CONCURRENT_ID-$CI_COMMIT_REF_SLUG
    paths:
      - ./deeploytest/TEST_*/build

run_siracusa_test_models: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  tags:
    - PULP
  needs:
    - job: build_deeploy
      artifacts: false
  parallel:
    matrix:
    - TEST: [simpleRegression, miniMobileNet, miniMobileNetv2, Attention]
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testRunner_siracusa.py -t ./Tests/$TEST --toolchain=$TOOLCHAIN --toolchain_install_dir=$LLVM_INSTALL_DIR --cores=8
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./deeploytest/out.txt
      - ./deeploytest/TEST_SIRACUSA/Tests/$TEST/*.c
      - ./deeploytest/TEST_SIRACUSA/Tests/$TEST/*.h
  cache:
    key: $CI_RUNNER_ID-$CI_CONCURRENT_ID-$CI_COMMIT_REF_SLUG
    paths:
      - ./deeploytest/TEST_*/build

run_siracusa_test_kernels: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  tags:
    - PULP
  needs:
    - job: build_deeploy
      artifacts: false
  parallel:
    matrix:
    - TEST: [Adder, MultIO, test1DPad, test2DPad, testMatMul, testMatMulAdd, testRequantizedDWConv, test2DRequantizedConv, iSoftmax]
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testRunner_siracusa.py -t ./Tests/$TEST --toolchain=$TOOLCHAIN --toolchain_install_dir=$LLVM_INSTALL_DIR
    # - python testRunner_siracusa.py -t ./Tests/testMaxPool
    # - python testRunner_siracusa.py -t ./Tests/testRequantizedConv
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./deeploytest/out.txt
      - ./deeploytest/TEST_SIRACUSA/Tests/$TEST/*.c
      - ./deeploytest/TEST_SIRACUSA/Tests/$TEST/*.h
  cache:
    key: $CI_RUNNER_ID-$CI_CONCURRENT_ID-$CI_COMMIT_REF_SLUG
    paths:
      - ./deeploytest/TEST_*/build

run_siracusa_DMA_slice_L2: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  tags:
    - PULP
  needs:
    - job: build_deeploy
      artifacts: false
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testSlice_PULP.py --toolchain=$TOOLCHAIN --toolchain_install_dir=$LLVM_INSTALL_DIR
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./deeploytest/out.txt
      - ./deeploytest/TEST_SIRACUSA/Tests/testSlice/*.c
      - ./deeploytest/TEST_SIRACUSA/Tests/testSlice/*.h
  cache:
    key: $CI_RUNNER_ID-$CI_CONCURRENT_ID-$CI_COMMIT_REF_SLUG
    paths:
      - ./deeploytest/TEST_*/build

run_siracusa_tiled_kernels_singlebuffer_L2: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  tags:
    - PULP
  needs:
    - job: build_deeploy
      artifacts: false
  parallel:
    matrix:
    - TEST: "testMatMul"
      L1: [64000, 32000, 16000]
    - TEST: "test2DRequantizedConv"
      L1: [8000, 6000, 4000]
    - TEST: "testRequantizedDWConv"
      L1: [2561] # SCHEREMO: The implicit transpose after the conv is untiled; need at least 2560
    - TEST: "iSoftmax"
      L1: [800, 500, 300]
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testRunner_tiled_siracusa.py -t ./Tests/$TEST --l1 $L1 --toolchain=$TOOLCHAIN --toolchain_install_dir=$LLVM_INSTALL_DIR --cores=8
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./deeploytest/out.txt
      - ./deeploytest/TEST_SIRACUSA/Tests/$TEST/*.c
      - ./deeploytest/TEST_SIRACUSA/Tests/$TEST/*.h
  cache:
    key: $CI_RUNNER_ID-$CI_CONCURRENT_ID-$CI_COMMIT_REF_SLUG
    paths:
      - ./deeploytest/TEST_*/build

run_siracusa_tiled_kernels_doublebuffer_L2: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  tags:
    - PULP
  needs:
    - job: build_deeploy
      artifacts: false
  parallel:
    matrix:
    - TEST: "testMatMul"
      L1: [64000, 32000, 16000]
    - TEST: "test2DRequantizedConv"
      L1: [8000, 6000, 5000]
    - TEST: "testRequantizedDWConv"
      L1: [5121] # SCHEREMO: The implicit transpose after the conv is untiled; need at least 2560 * 2 for DB
    - TEST: "iSoftmax"
      L1: [1600, 1000, 600]
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testRunner_tiled_siracusa.py -t ./Tests/$TEST --l1 $L1 --toolchain=$TOOLCHAIN --toolchain_install_dir=$LLVM_INSTALL_DIR --cores=8 --doublebuffer
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./deeploytest/out.txt
      - ./deeploytest/TEST_SIRACUSA/Tests/$TEST/*.c
      - ./deeploytest/TEST_SIRACUSA/Tests/$TEST/*.h
  cache:
    key: $CI_RUNNER_ID-$CI_CONCURRENT_ID-$CI_COMMIT_REF_SLUG
    paths:
      - ./deeploytest/TEST_*/build

run_siracusa_tiled_models_singlebuffer_L2: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  tags:
    - PULP
  needs:
    - job: build_deeploy
      artifacts: false
  parallel:
    matrix:
    - TEST: "simpleRegression"
      L1: [45000, 30000, 15000]
    - TEST: "miniMobileNet"
      L1: [60000, 12000, 6000, 3000]
    - TEST: "miniMobileNetv2"
      L1: [60000, 16000, 12000, 8000]
    - TEST: "Attention"
      L1: [60000, 10000, 5000, 2500]
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testRunner_tiled_siracusa.py -t ./Tests/$TEST --l1 $L1 --toolchain=$TOOLCHAIN --toolchain_install_dir=$LLVM_INSTALL_DIR --cores=8
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./deeploytest/out.txt
      - ./deeploytest/TEST_SIRACUSA/Tests/$TEST/*.c
      - ./deeploytest/TEST_SIRACUSA/Tests/$TEST/*.h
  cache:
    key: $CI_RUNNER_ID-$CI_CONCURRENT_ID-$CI_COMMIT_REF_SLUG
    paths:
      - ./deeploytest/TEST_*/build

run_siracusa_tiled_models_singlebuffer_L3: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  tags:
    - PULP
  needs:
    - job: build_deeploy
      artifacts: false
  parallel:
    matrix:
    - TEST: "simpleRegression"
      L1: [45000, 30000, 16000] # SCHEREMO: 15000 leads to non-2d transfers in L3!
    - TEST: "miniMobileNet"
      L1: [60000, 12000, 6000] # SCHEREMO: 3000 leads to non-2d transfers in L3!
    - TEST: "miniMobileNetv2"
      L1: [60000, 16000, 12000, 8000]
    - TEST: "Attention"
      L1: [60000, 10000, 5000, 2500]
    - TEST: "Transformer"
      L1: [60000, 30000, 15000]
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testRunner_tiled_siracusa.py -t ./Tests/$TEST --l1 $L1 --toolchain=$TOOLCHAIN --toolchain_install_dir=$LLVM_INSTALL_DIR --cores=8 --defaultMemLevel=L3
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./deeploytest/out.txt
      - ./deeploytest/TEST_SIRACUSA/Tests/$TEST/*.c
      - ./deeploytest/TEST_SIRACUSA/Tests/$TEST/*.h
  cache:
    key: $CI_RUNNER_ID-$CI_CONCURRENT_ID-$CI_COMMIT_REF_SLUG
    paths:
      - ./deeploytest/TEST_*/build


run_siracusa_tiled_models_doublebuffer_L3: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  tags:
    - PULP
  needs:
    - job: build_deeploy
      artifacts: false
  parallel:
    matrix:
    - TEST: "simpleRegression"
      L1: [60000, 45000, 30000]
    - TEST: "miniMobileNet"
      L1: [60000, 24000, 12000, 6000]
    - TEST: "miniMobileNetv2"
      L1: [60000, 32000, 24000, 16000]
    - TEST: "Attention"
      L1: [60000, 20000, 10000, 5000]
    - TEST: "Transformer"
      L1: [60000, 30000, 15000]
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testRunner_tiled_siracusa.py -t ./Tests/$TEST --l1 $L1 --toolchain=$TOOLCHAIN --toolchain_install_dir=$LLVM_INSTALL_DIR --cores=8 --doublebuffer --defaultMemLevel=L3
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./deeploytest/out.txt
      - ./deeploytest/TEST_SIRACUSA/Tests/$TEST/*.c
      - ./deeploytest/TEST_SIRACUSA/Tests/$TEST/*.h
  cache:
    key: $CI_RUNNER_ID-$CI_CONCURRENT_ID-$CI_COMMIT_REF_SLUG
    paths:
      - ./deeploytest/TEST_*/build


run_mempool_test_kernels: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  tags:
    - banshee
  needs:
    - job: build_deeploy
      artifacts: false
  retry: 2
  parallel:
    matrix:
    - TEST: [Adder, MultIO, test1DConvolution, test2DConvolution, test1DDWConvolution, test2DDWConvolution, test1DPad, test2DPad, testGEMM, testMatMul, testMatMulAdd, testMaxPool, testRQConv, testRQGEMM, testRQMatMul, testReduceSum, testReduceMean, testSlice, testRequantizedDWConv, test2DRequantizedConv]
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testRunner_mempool.py -t ./Tests/$TEST --toolchain=$TOOLCHAIN --toolchain_install_dir=$LLVM_INSTALL_DIR
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./deeploytest/out.txt
      - ./deeploytest/TEST_MEMPOOL/Tests/$TEST/*.c
      - ./deeploytest/TEST_MEMPOOL/Tests/$TEST/*.h
  cache:
    key: $CI_RUNNER_ID-$CI_CONCURRENT_ID-$CI_COMMIT_REF_SLUG
    paths:
      - ./deeploytest/TEST_*/build

run_mempool_test_models:   # This job runs in the test stage.
  stage: test              # It only starts when the job in the build stage completes successfully.
  tags:
    - banshee
  needs:
    - job: build_deeploy
      artifacts: false
  retry: 2
  parallel:
    matrix:
    - TEST: [simpleRegression, simpleCNN, ICCT, ICCT_ITA, miniMobileNet, miniMobileNetv2]
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testRunner_mempool.py -t ./Tests/$TEST --toolchain=$TOOLCHAIN --toolchain_install_dir=$LLVM_INSTALL_DIR
    # - python testRunner_mempool.py -t ./Tests/WaveFormer -DGCC_INSTALL_DIR=$MEMPOOL_GCC_INSTALL_DIR # Boken with ITA (heap is too small)
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./deeploytest/out.txt
      - ./deeploytest/TEST_MEMPOOL/Tests/$TEST/*.c
      - ./deeploytest/TEST_MEMPOOL/Tests/$TEST/*.h
  cache:
    key: $CI_RUNNER_ID-$CI_CONCURRENT_ID-$CI_COMMIT_REF_SLUG
    paths:
      - ./deeploytest/TEST_*/build

run_generic_test_kernels: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  needs:
    - job: build_deeploy
      artifacts: false
  parallel:
    matrix:
    - TEST: [Adder, MultIO, test1DConvolution, test2DConvolution, test1DDWConvolution, test2DDWConvolution, test1DPad, test2DPad, testGEMM, testMatMul, testMatMulAdd, testMaxPool, testRQConv, testRQMatMul, testReduceSum, testReduceMean, testSlice, testRequantizedDWConv, test2DRequantizedConv]
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testRunner_generic.py -t ./Tests/$TEST --toolchain=$TOOLCHAIN --toolchain_install_dir=$LLVM_INSTALL_DIR
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./deeploytest/out.txt
      - ./deeploytest/TEST_GENERIC/Tests/$TEST/*.c
      - ./deeploytest/TEST_GENERIC/Tests/$TEST/*.h
  cache:
    key: $CI_RUNNER_ID-$CI_CONCURRENT_ID-$CI_COMMIT_REF_SLUG
    paths:
      - ./deeploytest/TEST_*/build

run_generic_test_models:   # This job runs in the test stage.
  stage: test              # It only starts when the job in the build stage completes successfully.
  needs:
    - job: build_deeploy
      artifacts: false
  parallel:
    matrix:
    - TEST: [simpleRegression, WaveFormer, simpleCNN, ICCT, miniMobileNet, miniMobileNetv2]
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testRunner_generic.py -t ./Tests/$TEST --toolchain=$TOOLCHAIN --toolchain_install_dir=$LLVM_INSTALL_DIR
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./deeploytest/out.txt
      - ./deeploytest/TEST_GENERIC/Tests/$TEST/*.c
      - ./deeploytest/TEST_GENERIC/Tests/$TEST/*.h
  cache:
    key: $CI_RUNNER_ID-$CI_CONCURRENT_ID-$CI_COMMIT_REF_SLUG
    paths:
      - ./deeploytest/TEST_*/build

test_deeploy_state_serialization:
  stage: test
  needs:
    - job: build_deeploy
      artifacts: false
  parallel:
    matrix:
    - TEST: [simpleRegression]
      PLATFORM: ['QEMU-ARM', 'Siracusa', 'MemPool', 'Generic']
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python deeployStateEqualityTest.py -t ./Tests/$TEST -p $PLATFORM

test_memory_level_extension:
  stage: test
  needs:
    - job: build_deeploy
      artifacts: false
  parallel:
    matrix:
    - TEST: [simpleRegression]
      PLATFORM: ['QEMU-ARM', 'Siracusa', 'MemPool', 'Generic']
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testMemoryLevelExtension.py -t ./Tests/$TEST -p $PLATFORM

test_tiler_extension:
  stage: test
  needs:
    - job: build_deeploy
      artifacts: false
  parallel:
    matrix:
    - TEST: [simpleRegression, simpleCNN, testMatMul, testMaxPool]
      PLATFORM: ['Siracusa']
  script:
    - bash && source ~/.bashrc && source ~/.zshenv
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testTilerExtension.py -t ./Tests/$TEST -p $PLATFORM

test_tiler_extension_fails:
  stage: test
  needs:
    - job: build_deeploy
      artifacts: false
  parallel:
    matrix:
    - TEST: [simpleRegression, simpleCNN, testMatMul]
      PLATFORM: ['Siracusa']
  script:
    - bash && source ~/.bashrc && source ~/.zshenv
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testTilerExtension.py -t ./Tests/$TEST -p $PLATFORM --l1 2000 --shouldFail

test_memory_allocation_extension:
  stage: test
  needs:
    - job: build_deeploy
      artifacts: false
  parallel:
    matrix:
    - TEST: [simpleRegression, simpleCNN, miniMobileNet, miniMobileNetv2, testMatMul, testMaxPool]
      PLATFORM: ['Siracusa']
  script:
    - bash && source ~/.bashrc && source ~/.zshenv
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testTilerExtension.py -t ./Tests/$TEST -p $PLATFORM

test_deeploy_typing:
  stage: test
  needs:
    - job: build_deeploy
      artifacts: false
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testTypes.py

test_regex_matching:
  stage: test
  needs:
    - job: build_deeploy
      artifacts: false
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - cd deeploytest
    - python testRegexMatching.py

format_python:
  stage: lint
  needs:
    - job: build_deeploy
      artifacts: false
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - yapf -rpd Deeploy scripts

format_python_imports:
  stage: lint
  needs:
    - job: build_deeploy
      artifacts: false
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - isort Deeploy/*.py -c -v

format_c:
  stage: lint
  needs:
    - job: build_deeploy
      artifacts: false
  script:
    - bash && source ~/.bashrc
    - $CONDA activate dumpoci
    - python scripts/run_clang_format.py -e "*/third_party/*" -r Deeploy scripts
