[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "onnx",
    "mako",
    "numpy",
    "IPython"
    "nvidia-pyindex"
    "onnx-graphsurgeon"
]
build-backend = "setuptools.build_meta"