from .AllocateTemplate import *
from .ConvTemplate import *
from .DWConvTemplate import *
from .FreeTemplate import *
from .GemmTemplate import *
from .ITAMaxTemplate import *
from .MatMulTemplate import *
from .MaxPoolTemplate import *
from .MHSATemplate import *
from .RequantShiftTemplate import *
from .RQGemmTemplate import *
from .RQMatMulTemplate import *
